export const cards = [
  {
    id: 1,
    title: "House Helps",
    desc: "Make your work effortless",
    img: "https://thumbs.dreamstime.com/z/super-professional-cleaner-worker-concept-multitasking-cleaning-super-professional-cleaner-worker-girl-has-many-hands-190801379.jpg?ct=jpeg",
  },
  {
    id: 2,
    title: "Business Help",
    desc: "Grow your business",
    img: "https://thumbs.dreamstime.com/z/octopus-business-businessman-looks-like-36701676.jpg?ct=jpeg",
  },
  {
    id: 3,
    title: "Labour",
    desc: "Helping hands anytime",
    img: "https://thumbs.dreamstime.com/z/indian-old-man-working-laptop-computer-system-seating-agriculture-field-amazon-logo-displayed-mobile-phone-screen-online-157218308.jpg?ct=jpeg",
  },
  {
    id: 4,
    title: "Driver",
    desc: "Explore places on your comfort",
    img: "https://thumbs.dreamstime.com/z/dubai-uae-november-taxi-driver-dubai-summer-day-november-united-arab-emirates-taxi-driver-dubai-191734753.jpg?ct=jpeg",
  },
  {
    id: 5,
    title: "Home Tutions",
    desc: "Engage your children",
    img: "https://thumbs.dreamstime.com/z/classroom-6366284.jpg?ct=jpeg",
  },
  {
    id: 6,
    title: "Gardener",
    desc: "Maintain your greens",
    img: "https://thumbs.dreamstime.com/z/trimming-plants-outside-15984382.jpg?ct=jpeg",
  },
  {
    id: 7,
    title: "Care Taker",
    desc: "24X7 with your baby boomers",
    img: "https://thumbs.dreamstime.com/z/care-18956999.jpg?ct=jpeg",
  },
  {
    id: 8,
    title: "Salon at home",
    desc: "Pamper yourself in peace",
    img: "https://thumbs.dreamstime.com/z/asian-businessman-making-haircut-salon-home-outdoor-barbershop-garden-new-normal-lifestyle-social-distancing-191058292.jpg?ct=jpeg",
  },
];

export const projects = [
  {
    id: 1,
    img: "https://thumbs.dreamstime.com/z/two-little-girls-female-teacher-13356615.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Baby Sitter",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://thumbs.dreamstime.com/z/modern-analyst-looking-chart-graph-sales-rate-development-computer-monitor-analyzing-financial-statistics-100951922.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Business Analyst",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "https://thumbs.dreamstime.com/z/experience-childcare-as-should-be-caucasian-little-girl-spending-time-african-american-baby-sitter-drawing-187893925.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Home Tutor",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://thumbs.dreamstime.com/z/vintner-vineyard-16428409.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Gardner",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "https://thumbs.dreamstime.com/z/makeup-artist-work-12612419.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Makeup Artist",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://thumbs.dreamstime.com/z/elderly-care-nurse-helping-senior-wheel-chair-to-bed-71279626.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Care Taker",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "https://thumbs.dreamstime.com/z/pretty-very-busy-multitasking-housewife-white-background-32191317.jpg?ct=jpeg",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "House Help",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "https://media.gettyimages.com/id/1217751864/photo/nationwide-lockdown-to-curb-covid-19-pandemic.jpg?s=2048x2048&w=gi&k=20&c=vybvm1__SVwzj5KQpu6sh6goRzFhlnHR0iAX7kHA-Q0=",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Labour",
    username: "Ward Brewer",
  },
];

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];
